### ISSUE TITLE
STB-E7500 / STB-E7900 / STB-E7509S / STB-E7909S

### ISSUE THREAD

**Issue by Pauzi2304** [mmende/homebridge-samsungtv-control2#14]
Please add cable and SAT tuner STB-E7500 / STB-E7900 / STB-E7509S / STB-E7909S.

I have the cable tuner STB-E7900 wich was found by your discover function.

> pi@homebridge:/lib/modules $ homebridge-samsungtv-control discover
> Searching for devices...
> Found unparsable model name (E7900) for device [STB]E7900, usn: "uuid:0aba9501-00b4-1000-997a-c4731e756159". Skipping it.
> 😞 No Samsung TV found. Remember to turn on your Samsung TV's and check if they are connected to the same network before starting the discovery.

Thanks in advance!

**Comment by mmende** [comment]
I am thinking about that. The tuners would need to support one of the remote control protocols at least and then, I would have to extend the model parsing algorithm to also be able to parse tuner model numbers as well.

**Comment by Pauzi2304** [comment]
If you want, I can test the protocols for you.
Tell me what I have to change in your script.

**Comment by mmende** [comment]
The pairing / legacy scripts can already be tested and should show if the tuners can be controlled. You can run them like this:

`npx homebridge-samsungtv-control legacy <ip> <mac>`
`npx homebridge-samsungtv-control pair1 <ip> <mac>`
`npx homebridge-samsungtv-control pair2 <ip> <mac>`

e.g. `npx homebridge-samsungtv-control pair1 192.168.0.42 F3:0F:B3:9A:7C:FB`

However tuner support won't be top priority as long as there are other things to fix.

**Comment by Pauzi2304** [comment]
```
pi@homebridge:~ $ npx homebridge-samsungtv-control legacy XXX.XXX.X.XX XX:XX:XX:XX:XX:XX
Sending the mute key to see if your device is controlable with the legacy protocol over port 55000.
Device is off or unreachable
That didn't work unfortunatelly. Here are some other possible solutions:
	1. Try pairing method 1 npx homebridge-samsungtv-control pair1 XXX.XXX.X.XX XX:XX:XX:XX:XX:XX
	2. Try pairing method 2 npx homebridge-samsungtv-control pair2 XXX.XXX.X.XX XX:XX:XX:XX:XX:XX
```
```
pi@homebridge:~ $ npx homebridge-samsungtv-control pair1 XXX.XXX.X.XX XX:XX:XX:XX:XX:XX
That didn't work unfortunatelly. Here are some other possible solutions:
	1. Try pairing method 2 npx homebridge-samsungtv-control pair2 XXX.XXX.X.XX XX:XX:XX:XX:XX:XX
	2. Try the legacy protocol npx homebridge-samsungtv-control legacy XXX.XXX.X.XX XX:XX:XX:XX:XX:XX
```
```
pi@homebridge:~ $ npx homebridge-samsungtv-control pair2 XXX.XXX.X.XX XX:XX:XX:XX:XX:XX
Ok... sending the pairing request to your tv. Please click allow when asked
(node:28774) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
TV is off or unavalible
/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66
                throw new Error('Error send Key');
                ^

Error: Error send Key
    at /usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66:23
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:299:17)
    at WebSocket.emit (events.js:315:20)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/node_modules/ws/lib/websocket.js:551:15)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Ich schreib mal in Deutsch wenns erlaubt ist.
Ich habe gelesen, das du einen parser zum checken der Fernseher verwendest. Verwenden die pairing scripts auch diesen?

**Comment by mmende** [comment]
Nein... dafür werden nur die remote control libraries verwendet ohne irgendwelche checks... wenn die pairing bzw. legacy Methoden nicht funktionieren kann es leider sein, dass Samsung-Tuner dieses Feature einfach nicht unterstützen.
