### ISSUE TITLE
Samsung LE40A856 (2008) not found.

### ISSUE THREAD

**Issue by Pauzi2304** [mmende/homebridge-samsungtv-control2#15]
I tried to pair Samsung LE40A856

```
pi@homebridge:~ $ homebridge-samsungtv-control legacy 192.168.1.32 00:12:fb:1f:86:99
Sending the mute key to see if your device is controlable with the legacy protocol over port 55000.
Device is off or unreachable
That didn't work unfortunatelly. Here are some other possible solutions:
	1. Try pairing method 1 npx homebridge-samsungtv-control pair1 192.168.1.32 00:12:fb:1f:86:99
	2. Try pairing method 2 npx homebridge-samsungtv-control pair2 192.168.1.32 00:12:fb:1f:86:99
```

```
pi@homebridge:~ $ homebridge-samsungtv-control pair1 192.168.1.32 00:12:fb:1f:86:99
That didn't work unfortunatelly. Here are some other possible solutions:
	1. Try pairing method 2 npx homebridge-samsungtv-control pair2 192.168.1.32 00:12:fb:1f:86:99
	2. Try the legacy protocol npx homebridge-samsungtv-control legacy 192.168.1.32 00:12:fb:1f:86:99
```

```
pi@homebridge:~ $ homebridge-samsungtv-control pair2 192.168.1.32 00:12:fb:1f:86:99
Ok... sending the pairing request to your tv. Please click allow when asked
(node:19221) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
TV is off or unavalible
/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66
                throw new Error('Error send Key');
                ^

Error: Error send Key
    at /usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66:23
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:299:17)
    at WebSocket.emit (events.js:315:20)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/node_modules/ws/lib/websocket.js:551:15)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

So i made a portscan

```
Port Scanning host: 192.168.1.32

	 Open TCP Port: 	52396
```

Then I tried to pair again

```
pi@homebridge:~ $ homebridge-samsungtv-control legacy 192.168.1.32 00:12:fb:1f:86:99 --port 52396
Sending the mute key to see if your device is controlable with the legacy protocol over port 52396.
(node:19515) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.

That didn't work unfortunatelly. Here are some other possible solutions:
	1. Try pairing method 1 npx homebridge-samsungtv-control pair1 192.168.1.32 00:12:fb:1f:86:99
	2. Try pairing method 2 npx homebridge-samsungtv-control pair2 192.168.1.32 00:12:fb:1f:86:99
```

```
pi@homebridge:~ $ homebridge-samsungtv-control pair1 192.168.1.32 00:12:fb:1f:86:99 --port 52396
error: unknown option '--port'
```

```
pi@homebridge:~ $ homebridge-samsungtv-control pair2 192.168.1.32 00:12:fb:1f:86:99 --port 52396
Ok... sending the pairing request to your tv. Please click allow when asked
(node:19561) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.

/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66
                throw new Error('Error send Key');
                ^

Error: Error send Key
    at /usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66:23
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:299:17)
    at WebSocket.emit (events.js:315:20)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/node_modules/ws/lib/websocket.js:551:15)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Nothing found.

**Comment by mmende** [comment]
Hi. This model seems to be from 2008. I therefore unfortunately doubt it won't be possible to control it with the plugin as the remote control procotol seems to have been added to samsung tv's from 2011+.

**Comment by Pauzi2304** [comment]
I thought that 2008 models are supported.

**Comment by mmende** [comment]
That's at least how it looks like at the moment. I know for sure that one of my test devices from 2011 supports the legacy protocol and we tried to use the legacy protocol on a 2010 tv on every open port without success. Therefore it seems like this is the magic line for legacy protocol support. Sorry for not adding this information to the readme yet.

**Comment by Pauzi2304** [comment]
No problem!

**Comment by ggroel** [comment]
I have Samsung tv 2010 and use homebridge_upnp to control volume and samsung_tv for on/off state. Try it!

Gastón

**Comment by Pauzi2304** [comment]
Thank you for the hint. These plug-ins do not work with Samsung LE40A856 (2008). But now i can control Volume and see the on/off state of my Sasmung STB-E7900.
