### ISSUE TITLE
USN Number how can i find it

### ISSUE THREAD

**Issue by lukasj98** [mmende/homebridge-samsungtv-control2#16]
paring works and i get a token and the tv switches to mute but i can not find a usn number terminal is not showing it..
i did the paring with the command

**Comment by lukasj98** [comment]
i do not get any log in the logs

**Comment by mmende** [comment]
Could you try to start homebridge in debug mode? Some models don't expose their correct model number via upnp and will therefore not automatically be added as tv accessory.

**Comment by lukasj98** [comment]
how do i do it

**Comment by lukasj98** [comment]
i do not get any messages in the logs from your plugin

**Comment by lukasj98** [comment]
now i have debug mode on

**Comment by lukasj98** [comment]
but i do not get any logs from your plugin

**Comment by lukasj98** [comment]
can i chat with you in german

**Comment by mmende** [comment]
klar... siehst du log meldungen von anderen plugins?

**Comment by lukasj98** [comment]
ja ich wäre dir äußerst dankbar wenn wir das hinbekommen

**Comment by lukasj98** [comment]
könnten wir evtl skype mit bildschirmübertragung machen

**Comment by lukasj98** [comment]
oder teamviewer

**Comment by lukasj98** [comment]
hab schon so viele plugins probiert bei deinem funktioniert das paring

**Comment by mmende** [comment]
Ansonsten könntest du auch manuell mit `npx homebridge-samsungtv-control discover` überprüfen welche samsung fernseher das plugin findet... dort wird auch die usn angezeigt sofern der fernseher gefunden wurde

**Comment by lukasj98** [comment]
/homebridge # npx homebridge-samsungtv-control discover
Searching for devices...
(node:2908) UnhandledPromiseRejectionWarning: GotError: connect ECONNREFUSED 0.0.0.0:1901
    at onError (/homebridge/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/homebridge/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:2908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2908) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:2908) UnhandledPromiseRejectionWarning: GotError: connect ECONNREFUSED 0.0.0.0:1901
    at onError (/homebridge/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/homebridge/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:2908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
/homebridge #

**Comment by lukasj98** [comment]
was kann ich tun

**Comment by lukasj98** [comment]
nur das paring funktioniert

**Comment by mmende** [comment]
hm... der fehler ist neu. Ich melde mich wenn ich eine idee habe woran das liegen könnte

**Comment by lukasj98** [comment]
paring funktioniert einwandfrei bekomme token über die pair1 command methode

**Comment by lukasj98** [comment]
offentlich findet sich eine lösung

**Comment by lukasj98** [comment]
für mich als rollstuhlfahrer wäre es super auch noch den tv in homekit zu haben

**Comment by mmende** [comment]
Ich versuche gerade das problem einzugrenzen... könntest du bitte folgendes ausführen
`npx https://github.com/mmende/homebridge-samsungtv-control2#iss16 discover`
Das gibt uns hoffentlich ein paar genauere hinweise was das problem sein könnte...

**Comment by lukasj98** [comment]
/homebridge # npx https://github.com/mmende/homebridge-samsungtv-cont
rol2#iss16 discover
Searching for devices...
Got error while trying to check device with usn: "uuid:7272e15a-2505-11e5-b345-b2a15400ef00". GotError: connect ECONNREFUSED 0.0.0.0:1901
    at onError (/root/.npm/_npx/1260/lib/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/root/.npm/_npx/1260/lib/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'RequestError',
  code: 'ECONNREFUSED'
}
Found these devices:
[TV]Samsung LED40 (UE40H6400): usn "uuid:0f7f4902-0004-1000-b1b5-bc148513e64d"

**Comment by mmende** [comment]
Ok super...d.h. das Problem kommt wohl von einem anderen upnp device. Mit der nächsten Version sollte dieser Fehler zwar noch im debug log erscheinen, aber der Fernseher sollte trotzdem problemlos eingebunden werden können. Ich melde mich wenn ich diese gepublished habe...

**Comment by lukasj98** [comment]
Super vielen Dank dass du mich unterstützt und ich hoffe wir finden eine Lösung dass es bei mir funktioniert. Also kann ich bis zur nächsten Version den Fernseher noch nicht einbinden? 

Ich bekomme auch wie es in der Beschreibung des Plugins ins steht￼￼￼ keine automatischen Logs beim neu start ob tv gefunden werden. Erst mit dem command. Da das Paring aber einwandfrei funktioniert denke ich dass wir gemeinsam eine Lösung finden oder ?￼￼

**Comment by mmende** [comment]
Ja, das Problem liegt darin, dass bisher Fehler die an dieser Stelle entstehen nicht abgefangen wurden. Warum dieses Gerät den Fehler auslöst weiß ich immer noch nicht genau, aber solange der Fernseher davon nicht betroffen ist können wir das denke erstmal vernachlässigen. Bis ich die nächste Version publishe wird es noch ein paar Tage dauern, aber du könntest das Plugin auch direkt über github installieren: `npm i -g https://github.com/mmende/homebridge-samsungtv-control2` und schon mal prüfen ob der Rest dann normal durchläuft und der Fernseher z.B. in den logs auftaucht.

**Comment by lukasj98** [comment]
Ok also wie soll ich dann genau vorgehen?

**Comment by mmende** [comment]
Hast du die zuvor installierte Version vorher deinstalliert? Ich weiß nicht ob npm kapiert, dass es sich um das gleiche Modul handelt und dieses selbstständig deinstalliert wenn man über github installiert. Nach der installation über github Homebridge neustarten und erstmal schauen ob es in der plugin-section auftaucht. Optimalerweise tut es das und der Fernseher erscheint unter den homebridge accessories (sofern homebridge im insecure Mode gestartet wurde [siehe link](https://github.com/oznu/homebridge-config-ui-x#accessory-control))

**Comment by mmende** [comment]
Außerdem wird der TV falls alles klappt als externe Accessory eingebunden (wegen einer Homekit Limitation) weshalb man ihn getrennt von der Homebridge-Bridge in Homekit einbinden muss (siehe Readme).

**Comment by lukasj98** [comment]
mit getrennt meinst du das anpassen der config ?

**Comment by mmende** [comment]
Nein... nur, dass der Fernseher nicht mir der Bridge selbst in Homekit hinzugefügt wird sondern als eigenständiges Gerät (aber mit der gleichen Pin). Wenn man in der Home App auf das + klickt, dann Gerät hinzufügen, dann "Ich habe keinen Code bzw. kann nicht scannen" sollte der Fernseher dort auftauchen. Für die Homebridge-Bridge kann man ja einfach den QR-Code scannen. Für Fernseher muss man es aber so machen wie hier beschrieben.

**Comment by lukasj98** [comment]
bin gerade dabei das plugin über den command zu installieren

**Comment by lukasj98** [comment]
ist das bisher so richtig

**Comment by mmende** [comment]
Ja passt... die warnings kannst du ignorieren

**Comment by lukasj98** [comment]
und dann hab ich homebridge über (sudo) homebridge -I gestartet korrekt ? :)

**Comment by lukasj98** [comment]
und dann

**Comment by lukasj98** [comment]
ich habe schon viel probiert was sollte ich jetzt machen
danke dass du mich unterstützt

**Comment by mmende** [comment]
Siehst du irgendwelche log-Meldungen?

**Comment by lukasj98** [comment]
nein [8/2/2020, 11:48:28 AM] Loaded plugin: homebridge-config-ui-x@4.24.0
[8/2/2020, 11:48:28 AM] Registering platform 'homebridge-config-ui-x.config'
[8/2/2020, 11:48:28 AM] ---
[8/2/2020, 11:48:28 AM] ====================
[8/2/2020, 11:48:28 AM] ERROR LOADING PLUGIN homebridge-samsungtv-control:
[8/2/2020, 11:48:28 AM] Error: Cannot find module '/usr/local/lib/node_modules/homebridge-samsungtv-control/dist/index.js'
Require stack:
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:181:27)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:120:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:118:18)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:150:24)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
[8/2/2020, 11:48:28 AM] ====================
Setup Payload:
X-HM://0023ISYWYK49B
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[8/2/2020, 11:48:28 AM] Homebridge is running on port 33896.

**Comment by lukasj98** [comment]
plugin erscheint aber in  UI

**Comment by mmende** [comment]
Ah ok ... mein Fehler. Bei dem Master-Branch des repositories ist der Code noch nicht von Typescript zu Javascript umgewandelt enthalten. Du kannst aber den Branch nehmen den ich für dein Issue angelegt habe... einfach noch mal so installieren: `npm i -g https://github.com/mmende/homebridge-samsungtv-control2#iss16`

**Comment by lukasj98** [comment]
ok ich uninstall grad und install dann und sende dir dann wieder den log ok ?

**Comment by mmende** [comment]
👍

**Comment by lukasj98** [comment]
vielen dank irgendwann wird es klappen

**Comment by lukasj98** [comment]
[8/2/2020, 11:56:06 AM] [HB Supervisor] Restarting Homebridge...
[8/2/2020, 11:56:06 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules -D
[8/2/2020, 11:56:06 AM] [HB Supervisor] Started Homebridge v1.1.1 with PID: 1007
[8/2/2020, 11:56:07 AM] Loaded config.json with 0 accessories and 1 platforms.
[8/2/2020, 11:56:07 AM] ---
[8/2/2020, 11:56:08 AM] Loaded plugin: homebridge-dummy@0.4.1
[8/2/2020, 11:56:08 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[8/2/2020, 11:56:08 AM] ---
[8/2/2020, 11:56:08 AM] Loaded plugin: homebridge-config-ui-x@4.24.0
[8/2/2020, 11:56:08 AM] Registering platform 'homebridge-config-ui-x.config'
[8/2/2020, 11:56:08 AM] ---
[8/2/2020, 11:56:08 AM] Loaded plugin: homebridge-samsungtv-control@2.0.0-alpha.12
[8/2/2020, 11:56:08 AM] Registering platform 'homebridge-samsungtv-control.SamsungTVControl'
[8/2/2020, 11:56:08 AM] ---
[8/2/2020, 11:56:08 AM] Loading 1 platforms...
[8/2/2020, 11:56:08 AM] [Config] Initializing config platform...
[8/2/2020, 11:56:08 AM] [Config] Running in Service Mode
Setup Payload:
X-HM://0023ISYWYJNJL
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[8/2/2020, 11:56:08 AM] Homebridge is running on port 51687.
[8/2/2020, 11:56:20 AM] [Config] Starting terminal session

**Comment by mmende** [comment]
Kannst du homebridge noch mal im Debug-Mode starten?

**Comment by lukasj98** [comment]
also wie genau hab in UI einstellungen debug an

**Comment by lukasj98** [comment]
![image](https://user-images.githubusercontent.com/30393513/89120607-facc0600-d4b7-11ea-82cf-a3bda329894e.png)

**Comment by mmende** [comment]
Ah ok... ich wundere mich nur wo die Debug-Meldungen im Log bleiben

**Comment by lukasj98** [comment]
sudo homebridge debbug

**Comment by lukasj98** [comment]
hab ich grad gemacht

**Comment by lukasj98** [comment]
was soll ich tun

**Comment by mmende** [comment]
Ist das oben der gesamte Log?

**Comment by lukasj98** [comment]
hab nochmal restartet

**Comment by lukasj98** [comment]
was kann ich jetzt probieren

**Comment by mmende** [comment]
Kommt außer dem was du oben gepostet hattest nichts im log?

**Comment by lukasj98** [comment]
[8/2/2020, 12:05:13 PM] [HB Supervisor] OS: Linux 4.4.59+ x64
[8/2/2020, 12:05:13 PM] [HB Supervisor] Node.js v12.18.3 /usr/local/bin/node
[8/2/2020, 12:05:13 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[8/2/2020, 12:05:13 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[8/2/2020, 12:05:13 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules -D
[8/2/2020, 12:05:13 PM] [HB Supervisor] Started Homebridge v1.1.1 with PID: 1721
[8/2/2020, 12:05:13 PM] Loaded config.json with 0 accessories and 1 platforms.
[8/2/2020, 12:05:13 PM] ---
[8/2/2020, 12:05:14 PM] Loaded plugin: homebridge-dummy@0.4.1
[8/2/2020, 12:05:14 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[8/2/2020, 12:05:14 PM] ---
[8/2/2020, 12:05:14 PM] Loaded plugin: homebridge-config-ui-x@4.24.0
[8/2/2020, 12:05:14 PM] Registering platform 'homebridge-config-ui-x.config'
[8/2/2020, 12:05:14 PM] ---
[8/2/2020, 12:05:15 PM] Loaded plugin: homebridge-samsungtv-control@2.0.0-alpha.12
[8/2/2020, 12:05:15 PM] Registering platform 'homebridge-samsungtv-control.SamsungTVControl'
[8/2/2020, 12:05:15 PM] ---
[8/2/2020, 12:05:15 PM] Loading 1 platforms...
[8/2/2020, 12:05:15 PM] [Config] Initializing config platform...
[8/2/2020, 12:05:15 PM] [Config] Running in Service Mode
Setup Payload:
X-HM://0023ISYWYJNJL
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[8/2/2020, 12:05:15 PM] Homebridge is running on port 51687.
[8/2/2020, 12:05:16 PM] [Config] Homebridge Config UI X v4.24.0 is listening on :: port 8080
[8/2/2020, 12:05:21 PM] [Config] Starting terminal session
[8/2/2020, 12:05:33 PM] [Config] Terminal session ended.
[8/2/2020, 12:05:47 PM] [Config] Starting terminal session
[8/2/2020, 12:09:01 PM] [Config] Terminal session ended.
[8/2/2020, 12:09:04 PM] [Config] Starting terminal session
[8/2/2020, 12:10:34 PM] [Config] Terminal session ended.
[8/2/2020, 12:10:43 PM] [Config] Starting terminal session

**Comment by lukasj98** [comment]
nein

**Comment by lukasj98** [comment]
da kommt nichts anderes

**Comment by mmende** [comment]
Ok, dann gibt es wohl noch irgend ein anderes Problem... Ich gehe mal den Code durch und versuche rauszufinden wo beim initialisieren noch was schief laufen könnte und melde mich dann wieder.

**Comment by lukasj98** [comment]
ok hoffentlich klappt es ... vielen vielen dank schonmal

**Comment by lukasj98** [comment]
aber komisch ist dass ich keinen ordner von deinem plugin auf dem server finde unter node_modules

**Comment by mmende** [comment]
Das Plugin wurde ja global installiert (deshalb der `-g` Flag beim installieren)... d.H. der Ordner liegt im globalen node_modules Ordner.

**Comment by lukasj98** [comment]
![image](https://user-images.githubusercontent.com/30393513/89121386-d45d9900-d4be-11ea-93ed-0a6e9acb88f2.png)

**Comment by lukasj98** [comment]
hab nur diese drin

**Comment by lukasj98** [comment]
![image](https://user-images.githubusercontent.com/30393513/89121402-fa833900-d4be-11ea-9646-a893ba737ed0.png)

**Comment by lukasj98** [comment]
aber scheint ja installiert zu sein also liegt es am code

**Comment by lukasj98** [comment]
andere homebridge sachen haben ja funktioniert. ich hatte mal eine anderes plugin für lichter von osram in der homebridge das ging

**Comment by lukasj98** [comment]
also kann ich momentan das setup nicht machen ?

**Comment by lukasj98** [comment]
wenn ich versuche über config den tv einzubinden wie in der readme kommt immer dieser fehler 

(node:368) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at debug (/usr/local/lib/node_modules/homebridge/src/logger.ts:144:12)
    at checkDeviceDetails (/usr/local/lib/node_modules/homebridge-samsungtv-control/src/utils/detectDevices.ts:56:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:368) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:368) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at debug (/usr/local/lib/node_modules/homebridge/src/logger.ts:144:12)
    at checkDeviceDetails (/usr/local/lib/node_modules/homebridge-samsungtv-control/src/utils/detectDevices.ts:56:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by lukasj98** [comment]
hab jetzt versucht über discover und dann paring manuell  die config zu machen hab richtige usn nummer und token aber taucht nicht als gerät auf da muss noch ein fehler sein

**Comment by lukasj98** [comment]
8/2/2020, 1:39:05 PM] Registering platform 'homebridge-samsungtv-control.SamsungTVControl'
[8/2/2020, 1:39:05 PM] ---
[8/2/2020, 1:39:05 PM] Loading 2 platforms...
[8/2/2020, 1:39:05 PM] [Config] Initializing config platform...
[8/2/2020, 1:39:05 PM] [Config] Running in Service Mode
[8/2/2020, 1:39:05 PM] [SamsungTVControl] Initializing SamsungTVControl platform...
[8/2/2020, 1:39:05 PM] [SamsungTVControl] Got config {
  platform: 'SamsungTVControl',
  devices: [
    {
      usn: 'uuid:0f7f4902-0004-1000-b1b5-bc148513e64d',
      token: 'eyJzZXNzaW9uSWQiOiIxIiwiYWVzS2V5IjoiNGJkYjQ3YmM2NDkwZDBhNDZhNTAwMzM3NDZiNmUxNTIifQ==',
      name: 'Bedroom TV'
    }
  ]
}
[8/2/2020, 1:39:05 PM] [SamsungTVControl] Using node-persist path: /homebridge/.homebridge-samsungtv-control
Setup Payload:
X-HM://0023ISYWYJNJL
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[8/2/2020, 1:39:05 PM] Homebridge is running on port 51687.
[8/2/2020, 1:39:05 PM] [SamsungTVControl] SamsungTVControl db - /homebridge/.homebridge-samsungtv-control/49a93582a910673f04262657317b99d0 does not exist, returning undefined value
[8/2/2020, 1:39:07 PM] [Config] Homebridge Config UI X v4.24.0 is listening on :: port 8080
(node:368) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at debug (/usr/local/lib/node_modules/homebridge/src/logger.ts:144:12)
    at checkDeviceDetails (/usr/local/lib/node_modules/homebridge-samsungtv-control/src/utils/detectDevices.ts:56:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:368) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:368) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at debug (/usr/local/lib/node_modules/homebridge/src/logger.ts:144:12)
    at checkDeviceDetails (/usr/local/lib/node_modules/homebridge-samsungtv-control/src/utils/detectDevices.ts:56:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by lukasj98** [comment]
ich bin verzweifelt dabei aber ich glaub es liegt nicht am tv der dürfte kompatibel sein

**Comment by lukasj98** [comment]
Also am tv liegt es nicht

**Comment by mmende** [comment]
Hm ok ... ich schaue mal warum log nicht übergeben wird und sage dir bescheid wenn es gefixed wurde.

**Comment by lukasj98** [comment]
also in der library wird mein tv als unterstützes modell gelistet

**Comment by mmende** [comment]
Diese Fehlermeldung sollte auch nicht mehr mit der Library zu tun haben. Hab den Bug aber noch nicht gefunden...

**Comment by lukasj98** [comment]
ok. komisch dass ich das plugin gar nicht verwenden kann. aber hoffentlich findet sich die lösung

**Comment by lukasj98** [comment]
Gibt es schon Neuigkeiten?

**Comment by mmende** [comment]
Nein noch nicht. Was hattest du denn zuletzt angepasst (weil ja jetzt zumindest das Plugin geladen wird...wenn auch mit Fehlermeldung). Kann es sein, dass vorher in der Config unter platforms noch kein Objekt mit `{ "platform": "SamsungTVControl" ...` enthalten war?

**Comment by lukasj98** [comment]
Ja ich habe einfach mal wird die Config aus der readme aber mit eigenen Nummern passend zum tv aber funktioniert nicht ￼

**Comment by lukasj98** [comment]
?

**Comment by lukasj98** [comment]
https://github.com/kkapitan/homebridge-homesung 

dieses plugin funktioniert. aber da hab ich in homekit jede taste vom tv als switch und nicht den tv als tv mit den jeweiligen unteroptionen wie bei deinem plugin. kannst du mir weiterhelfen. 

ich wäre dir äußerst dankbar

**Comment by lukasj98** [comment]
ich kann dir auch die config schicken

**Comment by lukasj98** [comment]
wenn das plugin jetzt so wäre wie deins, dass es in homekit als tv mit fernbedienung angezeigt wird wäre es perfekt. bekommst du das hin

**Comment by lukasj98** [comment]
aber dann müsste man das doch auch in deinem schönen Plugin als Homekit TV hinbekommen. ?

**Comment by lukasj98** [comment]
?

**Comment by lukasj98** [comment]
wie ist der aktuelle Stand

**Comment by mmende** [comment]
Da ich das Plugin in meiner Freizeit entwickle kann ich leider nicht jeden Tag daran weiter arbeiten. Deshalb bitte ich um etwas Geduld bei der Lösung deines Problems. Ich melde mich wie gesagt wenn ich Neuigkeiten für dich habe.

**Comment by lukasj98** [comment]
?

**Comment by lukasj98** [comment]
???

**Comment by lukasj98** [comment]
??
