### ISSUE TITLE
I can't find token

### ISSUE THREAD

**Issue by yclai1229** [mmende/homebridge-samsungtv-control2#18]
Hi,My TV Device is (UA43MU6100), I cant find my token, 
There is a response in silent mode, but no token can be found.
how can I do? Thank you

homebridge@raspberrypi:/var/lib/homebridge $ npx homebridge-samsungtv-control pair1 192.168.1.xxx xx:xx:xx:xx:xx:xx
That didn't work unfortunatelly. Here are some other possible solutions:
        1. Try pairing method 2 npx homebridge-samsungtv-control pair2 192.168.1.xxx xx:xx:xx:xx:xx:xx
        2. Try the legacy protocol npx homebridge-samsungtv-control legacy 192.168.1.xxx xx:xx:xx:xx:xx:xx
homebridge@raspberrypi:/var/lib/homebridge $ npx homebridge-samsungtv-control pair2 192.168.1.xxx xx:xx:xx:xx:xx:xx
Ok... sending the pairing request to your tv. Please click allow when asked
(node:6544) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
That didn't work unfortunatelly. Here are some other possible solutions:
        1. Try another port npx homebridge-samsungtv-control pair2 192.168.1.xxx xx:xx:xx:xx:xx:xx --port 8001
        2. Try another port npx homebridge-samsungtv-control pair2 192.168.1.xxx xx:xx:xx:xx:xx:xx --port 55000
        3. Try the other pairing method npx homebridge-samsungtv-control pair1 192.168.1.xxx xx:xx:xx:xx:xx:xx
        4. Try the legacy protocol npx homebridge-samsungtv-control legacy 192.168.1.xxx xx:xx:xx:xx:xx:xx
homebridge@raspberrypi:/var/lib/homebridge $ npx homebridge-samsungtv-control pair2 192.168.1.xxx xx:xx:xx:xx:xx:xx --port 8001
Ok... sending the pairing request to your tv. Please click allow when asked

/usr/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66
                throw new Error('Error send Key');
                ^

Error: Error send Key
    at /usr/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66:23
    at WebSocket.<anonymous> (/usr/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:299:17)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnError (/usr/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/node_modules/ws/lib/websocket.js:777:13)
    at Receiver.emit (events.js:315:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at Receiver.startLoop (/usr/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/node_modules/ws/lib/receiver.js:152:5)
    at Receiver._write (/usr/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at Socket.socketOnData (/usr/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/node_modules/ws/lib/websocket.js:872:35)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
homebridge@raspberrypi:/var/lib/homebridge $ npx homebridge-samsungtv-control legacy 192.168.1.xxx xx:xx:xx:xx:xx:xx
Sending the mute key to see if your device is controlable with the legacy protocol over port 55000.
Device is off or unreachable
That didn't work unfortunatelly. Here are some other possible solutions:
        1. Try pairing method 1 npx homebridge-samsungtv-control pair1 192.168.1.xxx xx:xx:xx:xx:xx:xx
        2. Try pairing method 2 npx homebridge-samsungtv-control pair2 192.168.1.xxx xx:xx:xx:xx:xx:xx
homebridge@raspberrypi:/var/lib/homebridge $

**Comment by marcus-birju-sr** [comment]
I have the same issue. I cant find the token.

**Comment by mmende** [comment]
What do you mean with silent mode?

**Comment by yclai1229** [comment]
Hello, I will always show up the suggested method to obtain Token, but in the end it still cannot be obtained. And after I clicked Allow on my TV, nothing happened. Just keep repeating the above actions

1. Try another port npx homebridge-samsungtv-control pair2 192.168.1.xxx xx:xx:xx:xx:xx:xx --port 8001
2. Try another port npx homebridge-samsungtv-control pair2 192.168.1.xxx xx:xx:xx:xx:xx:xx --port 55000
3. Try the other pairing method npx homebridge-samsungtv-control pair1 192.168.1.xxx xx:xx:xx:xx:xx:xx
4. Try the legacy protocol npx homebridge-samsungtv-control legacy 192.168.1.xxx xx:xx:xx:xx:xx:xx

Keep repeating the prompt...but always can't find Token..

**Comment by aschi2** [comment]
I have the same problem, clicking allow results in 

That didn't work unfortunatelly. Here are some other possible solutions:
...

I've checked device connect manager on the tv and NodeJS Remote is set to allowed.

My model number is QN82Q65FN if that makes a difference.

**Comment by mmende** [comment]
I unfortunately don't have much influence on the actual libraries used to control the tv. If both of them are not able to control your tv chances are high that they just don't support your tv yet. The libraries being used are

* Option 1: [samsung-tv-control](https://github.com/Toxblh/samsung-tv-control) ... used for `pair2` and `legacy`
* Option 2: [samsung-remote-models-2014-and-newer](https://github.com/tdudek/samsung-remote-models-2014-and-newer) ([my fork](https://github.com/mmende/samsung-remote-models-2014-and-newer)) ... used for `pair1`

...if one of these libraries works with your tv but this plugin doesn't please let me know so I can fix the problem.

I know this is not the most satisfying answer and I would also love to support every samsung tv out of the box but I unfortunately don't have the time to dive deeper into the control part of the plugin other than adding more library options to this plugin.

**Comment by gradyhouston** [comment]
Oh, I know you can't support every single TV and I'd never expect that of you! My TV is a Q60R, which was released in 2019. So it's definitely a newer unit.

And yeah, I've tried those, unfortunately. I've tried all of those pairing options several times hoping they'd "just work".

**Comment by mmende** [comment]
Sorry to hear that it didn't work. I still hope that some day someone (or samsung themselves) publish a plugin that is able to control the whole samsung lineup.

**Comment by AlbertoAIG** [comment]
Could the SmartThing page that generates tokens be used to obtain one and that works with the QLEDs of 2019?

**Comment by rafacampoamor** [comment]
It seems that my TV works with legacy mode (I was prompted to allow the connection and got the mute state on the TV) but didn't return any token

`npx homebridge-samsungtv-control legacy 192.168.xxx.xx xx:xx:xx:xx:xx:xx
Sending the mute key to see if your device is controlable with the legacy protocol over port 55000.
Did the tv switch it's mute state? If yes then your tv supports the legacy protocol. Usually the plugin detects the appropriate port but you can also force this port by setting remoteControlPort to 55000

If it didn't work, here are some other possible solutions:
	1. Try pairing method 1 npx homebridge-samsungtv-control pair1 192.168.0.130 60:6b:bd:04:99:2a
	2. Try pairing method 2 npx homebridge-samsungtv-control pair2 192.168.0.130 60:6b:bd:04:99:2a
`

**Comment by jat80** [comment]
> It seems that my TV works with legacy mode (I was prompted to allow the connection and got the mute state on the TV) but didn't return any token
> 
> 
> 
> 
> 
> ```
> 
> npx homebridge-samsungtv-control legacy 192.168.xxx.xx xx:xx:xx:xx:xx:xx
> 
> Sending the mute key to see if your device is controlable with the legacy protocol over port 55000.
> 
> Did the tv switch it's mute state? If yes then your tv supports the legacy protocol. Usually the plugin detects the appropriate port but you can also force this port by setting remoteControlPort to 55000
> 
> 
> 
> If it didn't work, here are some other possible solutions:
> 
> 	1. Try pairing method 1 npx homebridge-samsungtv-control pair1 192.168.xxx.xx xx:xx:xx:xx:xx:xx
> 
> 	2. Try pairing method 2 npx homebridge-samsungtv-control pair2 192.168.xxx.xx xx:xx:xx:xx:xx:xx
> 
> ```
> 
> 
> 
> Obviously, I tried pair1 and 2 before legacy and got error on both (it's a 2012 TV model UE32D5500)

Did you manage to get this to work with your tv?

**Comment by rafacampoamor** [comment]
No, I couldn’t find any solution 😔

**Comment by tmur11** [comment]
@rafacampoamor did you end up figuring out how to enable/use legacy mode?!

**Comment by tmur11** [comment]
@jat80 did you ever have any luck with this? Seems like it should work consider the legacy mode test is described but a mystery how to use it..

**Comment by jat80** [comment]
No sorry
