### ISSUE TITLE
Plugin Start Error

### ISSUE THREAD

**Issue by m0dd3r43v3r** [mmende/homebridge-samsungtv-control2#23]
Not sure if I am not setting this up correctly but this is what I get after plugin installation and restarting the HomeBridge Service.

`(node:1488) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:1488) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/as-promise.js:118:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

**Comment by mmende** [comment]
How did you install homebridge and the plugin itself?

**Comment by mmende** [comment]
@gradyhouston can you tell me which app you use to control the tv from your iPhone?

**Comment by gradyhouston** [comment]
The SmartThings app (not the classic version). I can open the app and see my TVs in it and when connecting the TVs to that app, it pops up the "allow/deny" option. It doesn't allow me to control them, just pair/connect with them.
