### ISSUE TITLE
[DEP0123] DeprecationWarning

### ISSUE THREAD

**Issue by ericwongmusic** [mmende/homebridge-samsungtv-control2#24]
I installed the Samsungtv-control in my Hoobs server (BCM2835 - Pi 3 Model B) with Node v12.13.1 and NPM v6.14.8. My Samsung TV is 2014 model, note running Tizen. Does it support?

>/.hoobs/etc $ npx homebridge-samsungtv-control pair2 10.0.1.46 90:F1:AA:B1:9D:48
>Ok... sending the pairing request to your tv. Please click allow when asked
>(node:10561) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. >This will be ignored in a future version.
>TV is off or unavalible
>/home/hoobs/.hoobs/node_modules/samsung-tv-control/lib/samsung.js:66
>                throw new Error('Error send Key');
>                ^

>Error: Error send Key
>    at /home/hoobs/.hoobs/node_modules/samsung-tv-control/lib/samsung.js:66:23
>    at WebSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/samsung-tv-control/lib/samsung.js:299:17)
>    at WebSocket.emit (events.js:210:5)
>    at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/samsung-tv-control/node_modules/ws/lib/websocket.js:551:15)
>    at ClientRequest.emit (events.js:210:5)
>    at TLSSocket.socketErrorListener (_http_client.js:406:9)
>    at TLSSocket.emit (events.js:210:5)
>    at emitErrorNT (internal/streams/destroy.js:92:8)
>    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>    at processTicksAndRejections (internal/process/task_queues.js:80:21)

What does it mean? Not supported anymore? Thanks for the advice!

**Comment by mmende** [comment]
Can you try to pair with `pair1`? Kind regards

**Comment by LongSimple** [comment]
Have the same issue with pair2 sending a pair notification but not recognizing after I accept it on the TV.
