### ISSUE TITLE
Unable to get USN / UUID

### ISSUE THREAD

**Issue by PrimaryInc** [mmende/homebridge-samsungtv-control2#25]
Hi @mmende,

Thanks for creating plugin. Nice job 👍 
I did get the pair1 to work and i have token.
But I'm not able to get the USN / UUID, it is not presentet in the logs. 

Plugin loads:
![Samsung01](https://user-images.githubusercontent.com/45151934/91842142-c2a11a00-ec53-11ea-8f39-0e181c07a53b.PNG)

Pair works:
![Samsung02](https://user-images.githubusercontent.com/45151934/91842159-cd5baf00-ec53-11ea-9d63-c93e40ccf8e9.PNG)

But no USN / UUID in logs. 

Any pointers?

**Comment by mmende** [comment]
Nice to hear that pairing worked at least. Can you tell me the model number of your tv? It might not be covered by my model parser function yet.

**Comment by PrimaryInc** [comment]
Hi @mmende,

Thanks for getting back to me so quick 👍 
Modell is UE65HU7505

**Comment by PrimaryInc** [comment]
Hi @mmende ,

Another thing that would be great where to get the config posibillity to add condifg via the Home Bridge WEB UI:
If you want your plugin to show a config UI editor in the plugin homebridge-config-ui-x, you can add a file config.schema.json to the root of your plugin.

The specifications of that JSON schema are detailed in https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI

It's def not a mandatory thing to have in your plugin, but it helps many users that use that UI homebridge plugin to maintain their installation and don't want to mess up with JSON editing 😉

**Comment by mmende** [comment]
Ok the model number can be parsed and the tv is from 2014 (`npx homebridge-samsungtv-control model UE65HU7505`). Therefore the discovery seems to have problems discovering your tv. Can you try a manual discovery by running `npx homebridge-samsungtv-control discover` (note that this doesn't add the tv to homebridge but rather exists for debugging purposes...)

I already added a basic json schema but renamed it to `_config.schema.json` for now because you would have to wait for the device discovery anyway and I thought it might be more confusing to be confronted with the ui when you can't really add any configuration before knowing the parameters. However you could theoretically run the manual discovery before and acquire the usn's etc. before now. It might be a good idea to add it back and add some documentation for this way of setting it up. The json editing is also a good argument for doing so.

**Comment by PrimaryInc** [comment]
Hi @mmende,

I suggest a "good" instruction in web ui about steps needed to fill config page. Someone is bound to do it wrong anyways, but you know :)

Debugg info:
C:\Windows\System32>npx homebridge-samsungtv-control discover
Searching for devices...
(node:3120) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (C:\Users\kenneth\AppData\Roaming\npm\node_modules\homebridge-samsungtv-control\node_modules\got\dist\source\as-promise.js:118:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3120) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:3120) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (C:\Users\kenneth\AppData\Roaming\npm\node_modules\homebridge-samsungtv-control\node_modules\got\dist\source\as-promise.js:118:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

C:\Windows\System32>

**Comment by mmende** [comment]
Hm, seems to be the same error as in #23 ... I will have to figure out a way to reproduce this problem.

Concerning config ui:
I don't know if it is possible to add buttons with interactions within config ui but this would probably be the nicest solution.

**Comment by PrimaryInc** [comment]
Hi @mmende,
I tried to use http to se if my TV actually respondet to something:

![Samsung03](https://user-images.githubusercontent.com/45151934/91953901-98a63100-ed01-11ea-8434-fb1aa6ee6d93.PNG)

![Samsung04](https://user-images.githubusercontent.com/45151934/91953937-a065d580-ed01-11ea-8179-b904bb6d0ea0.PNG)

Is it a setting that might need to be enabled on the TV to get a response?

**Comment by PrimaryInc** [comment]
Ah if I use the whole string api/v2/ i get alot of information from the TV:
![Samsung05](https://user-images.githubusercontent.com/45151934/91954921-bfb13280-ed02-11ea-9a27-6b0288d62906.PNG)

Is the ID the same as USN / UUID?

**Comment by mmende** [comment]
Yes id seems to be the same. I saw some options to disable/enable network control on my tv's but the menu structure varies strongly across models.

You can find the file [here](https://raw.githubusercontent.com/mmende/homebridge-samsungtv-control2/master/_config.schema.json). However I didn't touch the file for some commits now and cannot guarantee that it fully works with the current configuration. The file is not being published at the moment, therefore you have to copy it to the location where the plugin is installed yourself (so in your case `C:\Users\kenneth\AppData\Roaming\npm\node_modules\homebridge-samsungtv-control`)

**Comment by PrimaryInc** [comment]
Hi @mmende,

I added the config file and added configuration:
![Samsung06](https://user-images.githubusercontent.com/45151934/91958944-4c122400-ed08-11ea-8ed4-e75f02ce4fab.PNG)

Config file:
![Samsung07](https://user-images.githubusercontent.com/45151934/91959046-6f3cd380-ed08-11ea-8e3c-317b83dc96c8.PNG)

Everything looks good, but I get error in log:
![Samsung08](https://user-images.githubusercontent.com/45151934/91959363-ccd12000-ed08-11ea-8ae5-df843f13afa3.PNG)

No butten apear in homeapp.

**Comment by mmende** [comment]
Yeah this is the same error as in #23 . This error seems to appear in the device discovery and will therefore lead to the plugin not being able to be loaded successfully. I will let you know (in this thread) when I know what's going on there.

**Comment by PrimaryInc** [comment]
@mmende thank you :)

**Comment by nidy86** [comment]
Hi @mmende,

Thanks for implementing this plugin. Nice Job done!

I think I've got the answer for this issue. 

Change your index.ts file like this:
`
import { API } from 'homebridge'
import { PLATFORM_NAME, PLUGIN_NAME } from './settings'
import { SamsungTVHomebridgePlatform } from './platform'

/**
 * This method registers the platform with Homebridge
 */
export = (api: API) => {
  api.registerPlatform(PLUGIN_NAME, PLATFORM_NAME, SamsungTVHomebridgePlatform)
}
`

now the plugin will be found. 

And for the impatient ones, here is a little work around:

1. Login to hoobs and open the terminal
2. enter "cd ../node_modules/homebridge-samsungtv-control/dist" to change to the right dir
3. enter nano index.js
4. now change following line:
`api.registerPlatform(settings_1.PLATFORM_NAME, platform_1.SamsungTVHomebridgePlatform);`
to
`api.registerPlatform(**settings_1.PLUGIN_NAME**, settings_1.PLATFORM_NAME, platform_1.SamsungTVHomebridgePlatform);`

**Comment by mmende** [comment]
Thank you very much for the hint. I'll see if I can add and test it later that day.

**Comment by PrimaryInc** [comment]
@mmende,
I see that a new release is out, but web config has changes a lot and does not contain the USN, token and name config part.
How is config suppose to look now?

Thanks!!

**Comment by mmende** [comment]
The config shouldn't have changed actually. Can you tell me which changes you mean exactly?

Kind regards

**Comment by PrimaryInc** [comment]
Noe it looks like this:

![Screenshot 2020-10-05 at 09 42 04](https://user-images.githubusercontent.com/45151934/95052333-0a054500-06ef-11eb-8cf2-5cf590d60ea9.png)

Before you can see a bit up this page.

**Comment by mmende** [comment]
The config should look the same as before e.g. like this:

```json
{
  "platform": "SamsungTVControl",
  "name": "SamsungTVControl",
  "devices": [
    {
      "usn": "uuid:a7001fbe-c776-11ea-87d0-0242ac130003",
      "name": "Bedroom TV",
      "token": "YOUR_PAIRING_TOKEN",
      "inputs": [
        {
          "name": "Sleep 30m",
          "keys": "tools,down*3,enter,down,enter,return"
        }
      ]
    }
  ]
}
```

...basically as described in the readme examples. I guess the new top level `name` property comes from a slightly changed function call that registers the plugin within homebridge. Apart from that all should be compatible with the current release.

**Comment by PrimaryInc** [comment]
Ok, thanks.
Strange the plugin UI dont show the same. I'll have a go manual config.

**Comment by mmende** [comment]
I didn't reactivate the schema json file yet because I want to extend the command line tools so far that you can get all infos you need upfront. Otherwise I suspect people to be a bit overwhelmed by the config screen with a lot of infos they don't have yet when they initially install the plugin.

**Comment by PrimaryInc** [comment]
Ah, yes that is correct. I'll look at enabeling the extention to see how it looks. I'm not to good with code.

**Comment by PrimaryInc** [comment]
Enabling web ui, I god this:
![Screenshot 2020-10-05 at 10 25 08](https://user-images.githubusercontent.com/45151934/95056456-0d033400-06f5-11eb-85ee-4a37178e00b6.png)

And it created this input to config:

![Screenshot 2020-10-05 at 10 23 59](https://user-images.githubusercontent.com/45151934/95056364-e5ac6700-06f4-11eb-990b-1b24eb1f65ba.png)

It is a bit different from what your config example and the device dont what up in Apple Home.
No error during restart :)
So I´ll try to change config manually to see if that helps.

**Comment by mmende** [comment]
Hm... it looks like you twisted usn and token and furthermore as far as I remember correctly the usn usually starts with `uuid:`. You can run `npx homebridge-samsungtv-control discover` to get the correct usn without needing to crawl through the homebridge log if that helps.

**Comment by PrimaryInc** [comment]
You are right, I did reverse them.
When trying the pair1, I don't get the UUID/USN presented in logs so I picked it up from http://tv_ip:8001/api/v2/ there it is shown without uuid:

![Screenshot 2020-10-05 at 10 57 52](https://user-images.githubusercontent.com/45151934/95059761-a03e6880-06f9-11eb-9794-d2f2e734e74d.png)

So I changed it, and let plugin UI do the config. 

![Screenshot 2020-10-05 at 10 57 11](https://user-images.githubusercontent.com/45151934/95059700-8735b780-06f9-11eb-8c56-472c3cc4893f.png)

No error on startup, plugin is loading, but there is no entry in log for Samsung TV other than this:
![Screenshot 2020-10-05 at 10 56 07](https://user-images.githubusercontent.com/45151934/95059586-61101780-06f9-11eb-9146-d9a2172ef65f.png)

**Comment by mmende** [comment]
Ok, did running `npx homebridge-samsungtv-control discover` list your tv?

**Comment by PrimaryInc** [comment]
I get this:

![Screenshot 2020-10-05 at 11 05 13](https://user-images.githubusercontent.com/45151934/95060511-a54fe780-06fa-11eb-95a8-a8a3ef9694f0.png)

This states a different uuid as well.

**Comment by mmende** [comment]
Hm ok ... this might also be another upnp device in your network and can be ignored if the usn differs. However as from the pictures above it seems like your tv does not expose the manufacturer field which this plugin currently uses to find out which upnp devices are possible samsung tv's. Therefore your tv might not be listed yet. I might remove this part in the next version as the plugin can also use the modelName property to identify samsung tv's (which your tv seems to expose as expected). I'll let you know when I published the next version with this fix included.

**Comment by PrimaryInc** [comment]
@mmende thanks :)

**Comment by PrimaryInc** [comment]
Just a quick update @mmende,
I did get the device in home kit, but it is not doing anything. 
That in it self is not strange sins tv is not connecting.

![IMG_1585](https://user-images.githubusercontent.com/45151934/98242884-67e6b000-1f6d-11eb-95d1-03a99ef54867.PNG)
