### ISSUE TITLE
UE65F9000 with SEK-3500 not showing in log

### ISSUE THREAD

**Issue by MartiMan79** [mmende/homebridge-samsungtv-control2#38]
Hi,

I successfully paired the TV with a PIN and a recognised MUTE command from a newly installed Homebridge setup.

I get following in the log:

**[11/23/2020, 3:09:07 PM] [HB Supervisor] Restarting Homebridge...
[11/23/2020, 3:09:07 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[11/23/2020, 3:09:07 PM] [HB Supervisor] Started Homebridge v1.1.6 with PID: 6855
[11/23/2020, 3:09:08 PM] Loaded config.json with 0 accessories and 2 platforms.
[11/23/2020, 3:09:08 PM] ---
[11/23/2020, 3:09:09 PM] Loaded plugin: homebridge-config-ui-x@4.34.0
[11/23/2020, 3:09:09 PM] Registering platform 'homebridge-config-ui-x.config'
[11/23/2020, 3:09:09 PM] ---
[11/23/2020, 3:09:09 PM] Loaded plugin: homebridge-samsungtv-control@2.0.0
[11/23/2020, 3:09:09 PM] Registering platform 'homebridge-samsungtv-control.SamsungTVControl'
[11/23/2020, 3:09:09 PM] ---
[11/23/2020, 3:09:09 PM] Loading 2 platforms...
[11/23/2020, 3:09:09 PM] [Config] Initializing config platform...
[11/23/2020, 3:09:09 PM] [Config] Running in Service Mode
[11/23/2020, 3:09:09 PM] [SamsungTVControl] Initializing SamsungTVControl platform...
Setup Payload:
X-HM://00252X4C4AFHB**

This is my config:

``{
    "platform": "SamsungTVControl",
    "name": "SamsungTVControl",
    "devices": [
        {
            "usn": "uuid:5855e8bc-0c31-4b5d-a13f-xxxxxxxxxxxx",
            "token": "eyJzZXNzaW9uSWQiOiIxIiwiYWVzS2V5IjoiMDU5Yjk2NmU3ZWZhZGRmY2U3ZGU1ZWI3MWY1xxxxxxxxxxxx",
            "name": "[TV] Living room TV",
            "inputs": [
                {
                    "name": "HDMI",
                    "keys": "hdmi"
                },
                {
                    "name": "ZDF HD",
                    "keys": "102"
                },
                {
                    "name": "Sleep 30m",
                    "keys": "tools,down*3,enter,down,enter,return"
                },
                {
                    "name": "Open YouTube",
                    "keys": "YouTube"
                }
            ]
        }
    ]
}``

/api/v2/ output

``{
  "id": "uuid:5855e8bc-0c31-4b5d-a13f-xxxxxxxxxxxx",
  "name": "[TV] Living room TV",
  "version": "2.0.25",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:5855e8bc-0c31-4b5d-a13f-xxxxxxxxxxxx",
    "model": "15_HAWKP_UHD_SEK",
    "modelName": "UE65F9000",
    "description": "Samsung DTV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "192.168.0.35",
    "firmwareVersion": "Unknown",
    "name": "[TV] Living room TV",
    "id": "uuid:5855e8bc-0c31-4b5d-a13f-xxxxxxxxxxxx",
    "udn": "uuid:5855e8bc-0c31-4b5d-a13f-xxxxxxxxxxxx",
    "resolution": "1920x1080",
    "countryCode": "LU",
    "msfVersion": "2.0.25",
    "smartHubAgreement": "true",
    "wifiMac": "50:85:69:xx:xx:xx",
    "developerMode": "0",
    "developerIP": ""
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.0.35:8001/api/v2/"
}`` 

No accessory shown in Homebridge and nothing recognised in the Homekit app.

Any idea?
Thanks in advance.

**Comment by mmende** [comment]
Can you test if the tv can be discovered with this command:

```sh
npx homebridge-samsungtv-control discover
```

**Comment by MartiMan79** [comment]
Thanks for the quick reply.

It has been "Searching for devices" for over 3 minutes...
Don't know how long it usually takes but guess this is not really what you wanted to hear😂

**Comment by MartiMan79** [comment]
Finally a result...

Searching for devices...
Got error while trying to check device with usn: "uuid:5bf091cc-4955-4398-aeb4-44a27fa888c4". GotError: connect ETIMEDOUT 10.123.176.1:9197
    at onError (/usr/lib/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/usr/lib/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  name: 'RequestError',
  code: 'ETIMEDOUT'
}
😞 No Samsung TV found. Remember to turn on your Samsung TV's and check if they are connected to the same network before starting the discovery.

**Comment by mmende** [comment]
Hm strange. No 3 minutes is not particularly the expected time it should take 😉. For me it takes about 6s.

It seems like the timeout appears when the discovery method tries to check the device description via upnp. Maybe there is some extra setting in the tv menu that disables other devices from fetching the device description via upnp...

**Comment by MartiMan79** [comment]
I think your plugin gets the wrong device type authorisation from the TV.
The myTifi app works and gets a "SLEEPsense" service authorisation in "Multimedia Device Manager" but Homebridge gets "Play Mobile Content on TV".
So I think the pairing gets a screen mirroring auth or so instead of a remote control auth.
In M-Search the xml files are accessible that hold the appropriate device description.

The 192.168.0.35 is the wired IP. 
The 2x 10.123.17x.1 are for Wifi direct? Not pingable though...

****************************************************************
SSDP reply message from 10.123.176.1:9197
XML file is located at http://10.123.176.1:9197/dmr
Device is running SHP, UPnP/1.0, Samsung UPnP SDK/1.0
****************************************************************

****************************************************************
SSDP reply message from 10.123.175.1:9197
XML file is located at http://10.123.175.1:9197/dmr
Device is running SHP, UPnP/1.0, Samsung UPnP SDK/1.0
****************************************************************

****************************************************************
SSDP reply message from 10.123.175.1:7679
XML file is located at http://10.123.175.1:7679/MainTVServer2/
Device is running SHP, UPnP/1.0, Samsung UPnP SDK/1.0
****************************************************************

****************************************************************
SSDP reply message from 192.168.0.35:9197
XML file is located at http://192.168.0.35:9197/dmr
Device is running SHP, UPnP/1.0, Samsung UPnP SDK/1.0
****************************************************************

****************************************************************
SSDP reply message from 192.168.0.35:7679
XML file is located at http://192.168.0.35:7679/MainTVServer2/
Device is running SHP, UPnP/1.0, Samsung UPnP SDK/1.0
****************************************************************

****************************************************************
SSDP reply message from 10.123.175.1:7676
XML file is located at http://10.123.175.1:7676/rcr/
Device is running SHP, UPnP/1.0, Samsung UPnP SDK/1.0
****************************************************************

****************************************************************
SSDP reply message from 192.168.0.35:7676
XML file is located at http://192.168.0.35:7676/rcr/
Device is running SHP, UPnP/1.0, Samsung UPnP SDK/1.0
****************************************************************

****************************************************************
SSDP reply message from 192.168.0.35:7678
XML file is located at http://192.168.0.35:7678/nservice/
Device is running SHP, UPnP/1.0, Samsung UPnP SDK/1.0
****************************************************************

**Comment by MartiMan79** [comment]
If you are interested, I made TCP dumps from the authorisation between the myTifi app and the TV and your plugin and the TV . 
Sadly this is beyond my comprehension but maybe it could be useful to you?
