### ISSUE TITLE
Samsung UE46F6670 (2013) not visible in accessoiries?

### ISSUE THREAD

**Issue by AndyVRD** [mmende/homebridge-samsungtv-control2#4]
Just tested the new alpha beta but my tv is not showing in the Homebridge UI-X accessories tab. In the logs it seems that the plugin founds my Tv...

[2020-7-17 22:40:39] [SamsungTVControl] Discovered TV "[TV] Samsung" with usn "uuid:XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
[2020-7-17 22:40:39] [SamsungTVControl] Found overwrites for "[TV] Samsung" in config
[2020-7-17 22:40:39] [SamsungTVControl] Samsung - Skipping pairing since this TV is from 2013 and should support the legacy protocol without pairing.

**Comment by mmende** [comment]
I actually encountered this problem myself also. It eventually just fixed itself and I still don't know why sometimes the registration of the tv accessory seems to fail. Hope I can fix the bug in the next release.

**Comment by mmende** [comment]
Did you give it another try with the latest updates? I haven't seen the problem reappearing on my end and would like to know if it still exists.

**Comment by ggroel** [comment]
root@NAS:~# npx homebridge-samsungtv-control pair2 10.0.1.3 E4:7C:F9:E8:58:B8 --port 8001
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/4181/lib/node_modules/homebridge-samsungtv-control/node_modules/fast-xml-parser/tasks/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Ok... sending the pairing request to your tv. Please click allow when asked
TV is off or unavalible
/root/.npm/_npx/4181/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66
                throw new Error('Error send Key');
                ^

Error: Error send Key
    at /root/.npm/_npx/4181/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66:23
    at WebSocket.<anonymous> (/root/.npm/_npx/4181/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:299:17)
    at WebSocket.emit (events.js:315:20)
    at ClientRequest.<anonymous> (/root/.npm/_npx/4181/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/node_modules/ws/lib/websocket.js:551:15)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:432:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Gastón

**Comment by ggroel** [comment]
with alpha11, 



but in tv not appear nothing pin

with pair2...



Gastón

**Comment by mmende** [comment]
@ggroel => https://github.com/mmende/homebridge-samsungtv-control2/issues/6#issuecomment-663594008

**Comment by AndyVRD** [comment]
> Did you give it another try with the latest updates? I haven't seen the problem reappearing on my end and would like to know if it still exists.

I can't install the latest alpha on Windows 10...

> te-models-2014-and-newer.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\
_logs\2020-07-26T08_54_03_973Z-debug.log

**Comment by mmende** [comment]
I just published v2.0.0-alpha.12 which hopefully let's you install the plugin without issues again. Could you tell me if you still encounter any of these errors with the new version?

**Comment by AndyVRD** [comment]
> I just published v2.0.0-alpha.12 which hopefully let's you install the plugin without issues again. Could you tell me if you still encounter any of these errors with the new version?

Tested and now it shows in accessories but the status is not showing if the Tv is on/off.

**Comment by mmende** [comment]
You mean the on/off state?
