### ISSUE TITLE
Samsung F5370 weird pairing behavior/ no pairing

### ISSUE THREAD

**Issue by WolfMa99** [mmende/homebridge-samsungtv-control2#42]
Hello,

I got a Samsung F5370 with the version 2127 installed. I also have Homebridge successfully running and installed your plugin. The plugin doesn't show me the TV.

If I run the discover command manually on the shell, it doesn't find it.
With the legacy command it issues the mute key on the TV and the TV shows a message to allow or decline the request, the picture is attached. The command tells to set port to 55000. 
Than I run pair2 with the port set to 55000 and again the TV shows the message to allow the request, but the command just continues and doesn't wait, than I can click accept on the TV and if I rerun the command it shows the same behavior, except it doesn't bring back the request on the TV.

I hope you can help me. I am also German. 
![Bildschirmfoto 2020-11-27 um 09 17 42](https://user-images.githubusercontent.com/36261965/100427254-7e76b780-3092-11eb-85e8-6ac866e6fed5.png)
![IMG_0787](https://user-images.githubusercontent.com/36261965/100427343-9a7a5900-3092-11eb-8c76-bb3a2fc3d744.jpeg)

**Comment by mpjalexander** [comment]
I have a similar issue. In addition, when I try the `pair2` method, I see the following error:
`Ok... sending the pairing request to your tv. Please click allow when asked
TV is off or unavalible
/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:55
                throw new Error('Error send Key');
                ^

Error: Error send Key
    at /usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:55:23
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:279:17)
    at WebSocket.emit (events.js:315:20)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/node_modules/ws/lib/websocket.js:579:15)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`
