### ISSUE TITLE
Slow down error in HB log

### ISSUE THREAD

**Issue by PrimaryInc** [mmende/homebridge-samsungtv-control2#55]
Hi,

just noticed that i get a warning messages in HB that the this plugin slows down homebridge.

![Slowdown](https://user-images.githubusercontent.com/45151934/109275001-6ee34800-7814-11eb-9238-7fb7af755ff9.PNG)

https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings

I've installed plugin but never got it to work as expected. Was hoping for a fix, but do understand it is time consuming and perhaps not even possible to fix. Non the less, just wanted to update you on the message from HB logs :)

**Comment by TheEngineerGuy** [comment]
Which version of HB are you running?

**Comment by PrimaryInc** [comment]
Hi, v 1.3.2, latest as of now.

**Comment by TheEngineerGuy** [comment]
Are you not getting this error in you HB since 1.3.0?

`TypeError: Cannot read property 'log' of undefined at debug (/usr/lib/node_modules/homebridge/src/logger.ts:143:10) at checkDeviceDetails (/usr/lib/node_modules/homebridge-samsungtv-control/src/utils/detectDevices.ts:85:5) at processTicksAndRejections (node:internal/process/task_queues:93:5)`

**Comment by PrimaryInc** [comment]
I did noticed message in logs after upgrading from 1.2.7 to 1.3.1 and stil present in 1.3.2
Now my HB works fine, but not sure if performance is severely impaired.

**Comment by TheEngineerGuy** [comment]
hmm... so you still see that error in 1.3.2, but it is not stuck in restart loop? Weird, I tried 1.3.2 this morning and it was still restart looping after throwing that error.

**Comment by TheEngineerGuy** [comment]
Can you paste your config for this plugin here? Maybe I have something unwanted in my config.

**Comment by PrimaryInc** [comment]
{
            "devices": [
                {
                    "name": "TV Livingroom",
                    "usn": "UUID",
                    "token": "string",
                    "delay": 100
                }
            ],
            "platform": "SamsungTVControl"
        }
        
This is what I have, but I dont get my pairing to work, I have a open issue on that as well. Might be the reason that my does not loop. Removed UUID and Token from config over.

**Comment by TheEngineerGuy** [comment]
Other than me never having to use Token and delay our configs are identical. My hunt continues. And hopefully @mmende can take a peek.

**Comment by PrimaryInc** [comment]
#25 ia my other issue if makes any sence to look at it.

**Comment by mmende** [comment]
@TheEngineerGuy The `...property 'log' of undefined...` issue should now hopefully be fixed with the latest patch (v2.0.2). This however does not fix the slow down error. I guess homebridge initially requests all characteristics at once and the subsequent  processing of all of these requests by the connected TV's just takes too long which is then interpreted as timeout.

**Comment by iperniaf** [comment]
property 'log' of undefined fixed for me
thx @mmende
