### ISSUE TITLE
UE467700 does not work in 2.0.0 (did well in 1.1.1)

### ISSUE THREAD

**Issue by Reinboeng** [mmende/homebridge-samsungtv-control2#56]
Hi Martin (@mmende),

thanks for your long term work regarding this plugin.

I recently tried to update the plugin from 1.1.1 to a newer version (2.0.0), but I failed.

What I did:
1. Upgraded the plugin via config-ui-x UI.
2. Removed the old (1.1.1) config from config.json
3. Added the new config "{"platform": "SamsungTVControl", "name": "SamsungTVControl"} to the config.json
5. Added initial config to config.json ("devices": [{"usn": "uuid:a7001fbe-c776-11ea-87d0-0242ac130003", "name": "Bedroom TV"}]
4. Switched HB debug mode on.
6. Restarted HB
5. Did the paring "npx homebridge-samsungtv-control legacy 192.168.0.26 00:12:fb:21:8a:8b". TV was muted.
6. Did not get any UUID (in hb.log).
7. Tried to add TV to my Home (Open the Home App, Type + in the top right corner to add a device, Then click on Don't Have a Code or Can't scan?, The found TV should appear under Nearby Accessories ... click on it)

No success. 

All I can see in the logs are two related entries:
^[[37m[07/03/2021, 20:13:32] ^[[39m^[[36m[SamsungTVControl]^[[39m ^[[90mGot config {^[[39m
^[[90m  platform: 'SamsungTVControl',^[[39m
^[[90m  devices: [^[[39m
^[[90m    {^[[39m
^[[90m      usn: 'uuid:a7001fbe-c776-11ea-87d0-0242ac130003',^[[39m
^[[90m      name: 'SamsungTV'^[[39m
^[[90m    }^[[39m
^[[90m  ]^[[39m
^[[90m}^[[39m

^[[37m[07/03/2021, 20:13:32] ^[[39m^[[36m[SamsungTVControl]^[[39m ^[[90mUsing node-persist path: /var/lib/homebridge/.homebridge-samsungtv-con$
(node:10133) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at debug (/usr/local/lib/node_modules/homebridge/src/logger.ts:143:10)
    at checkDeviceDetails (/usr/local/lib/node_modules/homebridge-samsungtv-control/src/utils/detectDevices.ts:85:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async functi$
(node:10133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, p

Hope this helps and you may solve my issue!

Thank you! Regards!

Lars

**Comment by mmende** [comment]
Seems to be the same issue as #66
I just published a patch including a workaround for this specific problem. Let me know if v2.0.2 fixed the problem.

**Comment by Reinboeng** [comment]
###Log Output
`Found unparsable model name (Samsung DTV DMR) for device TV-46C7700, usn: "uuid:nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn". Skipping it.` (I changed uuid to n's).

### Config
```
        {
            "platform": "SamsungTVControl",
            "devices": [
                {
                    "usn": "uuid:7593195a-d865-5896-0fef-1439766e4e83",
                    "name": "Samsung TV"
                }
            ]
        }

```

Unfortunately I am not able to add the TV as described (+ and so an). It is not found.

**Comment by Reinboeng** [comment]
Hi @mmende ,

even if I try to override the discovered modelName "Samsung DTV DMR" for the device stated in the log it is not recognized:

`Found unparsable model name (Samsung DTV DMR) for device TV-46C7700, usn: "uuid:7593195a-d865-5896-0fef-1439766e4e83". Skipping it.
`
```
    {
        "platform": "SamsungTVControl",
        "devices": [
            {
                "usn": "uuid:7593195a-d865-5896-0fef-1439766e4e83",
                "name": "TV-46C7700",
                "modelName": "UE46C7700WSXZG"
            }
        ]
    }
```
results in
```
Found config for unknown device usn: "uuid:7593195a-d865-5896-0fef-1439766e4e83" {
  usn: 'uuid:7593195a-d865-5896-0fef-1439766e4e83',
  name: 'TV-46C7700',
  modelName: 'UE46C7700WSXZG'
}
```

Help would be appreciated!

**Comment by mussolene** [comment]
maybe HB settings problem?
go to the HB settings and reset settings accessory.?
