### ISSUE TITLE
Pairing issue

### ISSUE THREAD

**Issue by janhuehne** [mmende/homebridge-samsungtv-control2#76]
I am always getting this exception. Any hints?

`npx homebridge-samsungtv-control pair1 192.168.178.23 CC:B1:1A:62:F6:8F`

 `(node:1673) UnhandledPromiseRejectionWarning: Error: Unable to handleEvent
    at /usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote-pin-paired/lib/Connection/SamsungTvConnection.js:130:13
    at /usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote-pin-paired/lib/Connection/Messages.js:30:31
    at new Promise (<anonymous>)
    at Messages.handle (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote-pin-paired/lib/Connection/Messages.js:29:12)
    at onMessageEmitter (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote-pin-paired/lib/Connection/SamsungTvConnection.js:45:12)
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote-pin-paired/lib/Connection/SamsungTvConnection.js:157:9)
    at WebSocket.emit (events.js:310:20)
    at Receiver._receiver.onmessage (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/ws/lib/websocket.js:137:47)
    at Receiver.dataMessage (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/ws/lib/receiver.js:409:14)
    at Receiver.getData (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/ws/lib/receiver.js:347:12)
    at Receiver.startLoop (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/ws/lib/receiver.js:143:16)
    at Receiver.add (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/ws/lib/receiver.js:117:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
(node:1673) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1673) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by phluorine** [comment]
Same here. 2016 6 Series 4k SmartTV (UN60KU6270).
