### ISSUE TITLE
Unable to pair UE65KS8005

### ISSUE THREAD

**Issue by vannman** [mmende/homebridge-samsungtv-control2#82]
When trying to pair my Samsung 8 Series (65)" (UE65KS8005) I get the following error:

```
npx homebridge-samsungtv-control pair1 192.168.1.191 5c:49:7d:52:97:b9
Please enter the pin you see on your tv
8193
Ok... sending "8193" to your tv to see if it works...
(node:64881) UnhandledPromiseRejectionWarning: Error: Unable to handleEvent
    at /usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote-pin-paired/lib/Connection/SamsungTvConnection.js:130:13
    at /usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote-pin-paired/lib/Connection/Messages.js:30:31
    at new Promise (<anonymous>)
    at Messages.handle (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote-pin-paired/lib/Connection/Messages.js:29:12)
    at onMessageEmitter (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote-pin-paired/lib/Connection/SamsungTvConnection.js:45:12)
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-remote-pin-paired/lib/Connection/SamsungTvConnection.js:157:9)
    at WebSocket.emit (events.js:375:28)
    at Receiver._receiver.onmessage (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/ws/lib/websocket.js:137:47)
    at Receiver.dataMessage (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/ws/lib/receiver.js:409:14)
    at Receiver.getData (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/ws/lib/receiver.js:347:12)
    at Receiver.startLoop (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/ws/lib/receiver.js:143:16)
    at Receiver.add (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/ws/lib/receiver.js:117:10)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:64881) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:64881) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^X^C
```

Using pair2 seems to work and I am able to add the TV in Home, but when sending commands I get the following error in the home bridge logs:

```
[12/26/2021, 9:55:55 AM] [SamsungTVControl] [TV] Samsung 8 Series (65) - SET Active => setNewValue: 1
[12/26/2021, 9:55:58 AM] [homebridge-samsungtv-control] Error: 
    at Accessory.sendCharacteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1874:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1581:14)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

Any ideas?

**Comment by vannman** [comment]
Also get this error when restarting homebridge:

```
Got error while trying to check device with usn: "uuid:7272e15a-2505-11e5-b345-0edc5500ef00". GotError: connect ECONNREFUSED 0.0.0.0:1901
    at onError (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  name: 'RequestError',
  code: 'ECONNREFUSED'
}

```

**Comment by chridefix** [comment]
hello,

i got it working once, then i recognized that in apple remote app not all buttons are working - so i thought it would be a good idea to beginn from new.. yeah.. bad idea.. know i have the same issue like you. i would love to here if you found a solution

**Comment by DawieLombaard** [comment]
Hi @vannman, from what I can see, your television runs Tizen OS.

Have you tried this plugin instead "Homebridge Samsung Tizen" (homebridge-samsung-tizen)? My Tizen OS television works perfectly using that plugin.

The problem is that Samsung changed their API and I believe the errors you're getting is because of the changes between them. If you'd still like to use this plugin, I'd suggest either waiting for the DEVs to support the new API, or dig into the code yourself.

I hope this helps a bit.
