### ISSUE TITLE
Can't control TV, successfully added though!?

### ISSUE THREAD

**Issue by dfizzo** [mmende/homebridge-samsungtv-control2#90]
Hi - I am struggling to control 2016 Samsung UN65JU6500 model. I ran pair1 and successfully entered PIN and got mute control. And grabbed UUID from the log. The TV shows in HomeKit but I can't control device (power off or volume, etc.). Below is what I am seeing in the log. Any guidance? Much appreciated!

+++++

[4/1/2022, 2:43:12 PM] [homebridge-samsungtv-control] This plugin generated a warning from the characteristic 'Mute': Characteristic not in required or optional characteristic section for service Television. Adding anyway..
See https://git.io/JtM
GR for more info.
[4/1/2022, 2:43:12 PM] [homebridge-samsungtv-control] This plugin generated a warning from the characteristic 'Volume': Cracteristic not in required or optional characteristic section for service Television. Adding anyway.. See https://git.io/J
MGR for more info

**Comment by dfizzo** [comment]
FWIW: HomeKit icon for the TV does correctly show if the device is on/off (as controlled manually via television remote). But cannot control the TV device via HomeKit or co from center remote

**Comment by kisgamer** [comment]
I'm having the exact same problem.

**Comment by tatermysalad** [comment]
Me too! Mine is continuously stuck on muting the TV. Ran in debug mode I get the additional:
[10/13/2022, 3:22:45 AM] [SamsungTVControl] Samsung TV - GET Active
[10/13/2022, 3:22:45 AM] [SamsungTVControl] Samsung TV - GET Mute
[10/13/2022, 3:22:45 AM] [SamsungTVControl] Samsung TV - GET Volume
[10/13/2022, 3:22:45 AM] [SamsungTVControl] Samsung TV - GET Active
[10/13/2022, 3:22:45 AM] [SamsungTVControl] Samsung TV - GET Mute
[10/13/2022, 3:22:45 AM] [SamsungTVControl] Samsung TV - GET Volume

[10/13/2022, 3:22:45 AM] [homebridge-samsungtv-control] This plugin slows down Homebridge. The write handler for the characteristic 'Mute' on the accessory 'Samsung TV 806F' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.

[10/13/2022, 3:24:51 AM] [homebridge-samsungtv-control] Error: 
    at Accessory.sendCharacteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1947:14)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1642:14)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
